ecommerce/apps/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

ecommerce/apps/checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ecommerce.apps.catalogue.urls", namespace="catalogue")),
    path("checkout/", include("ecommerce.apps.checkout.urls", namespace="checkout")),
    path("basket/", include("ecommerce.apps.basket.urls", namespace="basket")),
    path("account/", include("ecommerce.apps.account.urls", namespace="account")),
    path("orders/", include("ecommerce.apps.orders.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/apps/checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

ecommerce/apps/checkout/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from ecommerce.apps.account.models import Address
from ecommerce.apps.basket.basket import Basket
from ecommerce.apps.orders.models import Order, OrderItem

from .models import DeliveryOptions


@login_required
def deliverychoices(request):
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    return render(request, "checkout/delivery_choices.html", {"deliveryoptions": deliveryoptions})


@login_required
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        delivery_option = int(request.POST.get("deliveryoption"))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)

        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": delivery_type.id,
            }
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True

        response = JsonResponse({"total": updated_total_price, "delivery_price": delivery_type.delivery_price})
        return response


@login_required
def delivery_address(request):

    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = Address.objects.filter(customer=request.user).order_by("-default")

    if "address" not in request.session:
        session["address"] = {"address_id": str(addresses[0].id)}
    else:
        session["address"]["address_id"] = str(addresses[0].id)
        session.modified = True

    return render(request, "checkout/delivery_address.html", {"addresses": addresses})


@login_required
def payment_selection(request):

    session = request.session
    if "address" not in request.session:
        messages.success(request, "Please select address option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    return render(request, "checkout/payment_selection.html", {})


####
# PayPay
####
from paypalcheckoutsdk.orders import OrdersGetRequest

from .paypal import PayPalClient


@login_required
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body["orderID"]
    user_id = request.user.id

    requestorder = OrdersGetRequest(data)
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value

    basket = Basket(request)
    order = Order.objects.create(
        user_id=user_id,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        address1=response.result.purchase_units[0].shipping.address.address_line_1,
        address2=response.result.purchase_units[0].shipping.address.admin_area_2,
        postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        country_code=response.result.purchase_units[0].shipping.address.country_code,
        total_paid=response.result.purchase_units[0].amount.value,
        order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order_id = order.pk

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])

    return JsonResponse("Payment completed!", safe=False)


@login_required
def payment_successful(request):
    basket = Basket(request)
    basket.clear()
    return render(request, "checkout/payment_successful.html", {})

templates/checkout/delivery_address.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>


<div class="container">
  <div class="row g-3">
    {% if addresses|length == 0 %}
    <div class="col-12">There are no delivery addresses, <a href="{% url 'account:add_address' %}">add address</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
    
<div class="d-flex bd-highlight ms-0">
  <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
</div>
<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price" class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
</div>
<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"class="fw-bold h5">{{basket.get_total_price}}</span></div>
</div>
<a role="button" href="{% url 'checkout:payment_selection' %}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
</div>
    
    <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
        <h1 class="h5 pt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
                &nbsp;
              </div>
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  <a href="{% url 'account:edit_address' address.id %}" class="text-decoration-none">Edit</a>
                  {% if not address.default %}
                  | <a href="{% url 'account:set_default' address.id %}" class="text-decoration-none">Select</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock %}

templates/checkout/delivery_choices.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Select your delivery options</p>
  </div>
  <hr />
</div>


<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
  {% for message in messages  %}
    {{message|safe}}
  {% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    {% if deliveryoptions|length == 0 %}
    <div class="col-12">There are no delivery options <a href="{% url 'store:store_home' %}">Shop</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div>
      <a role="button" href="{% url "checkout:delivery_address" %}" class="btn btn-success fw-bold w-100"
        type="button">Pay Securely</a>
    </div>
    <div class="col-md-7 col-lg-8">
      {% for option in deliveryoptions %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col-md-2 ps-3 ps-md-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
              viewBox="0 0 16 16">
              <path
                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
          </div>
          <div class="col-md-9 ps-md-1">
            <div class="card-body p-1">
              <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</p>
              <p class="card-text ps-2 pb-3">Your order should be delivered within {{option.delivery_timeframe}}</p>
            </div>
          </div>
          <div class="col-md-1 ps-md-1">
            <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{option.id}}"
              value="{{option.id}}">
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

<script>
  $('input[type=radio][name=deliveryOption]').on('change', function(e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "checkout:basket_update_delivery" %}',
      data: {
        deliveryoption: $(this).val(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("total").innerHTML = json.total;
        document.getElementById("delivery_price").innerHTML = json.delivery_price;
      },
      error: function (xhr, errmsg, err) {},
    });
    
  });
</script>


{% endblock %}

templates/checkout/payment_selection.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Selection{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
     <h1 class="h2">Payment Selection</h1>
  </div>
  <div class="col-12">
    <p>Please select your payment option</p>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
      <div id="paypal-button-container"></div>
    </div>
  </div>
</div>
<script
  src="https://www.paypal.com/sdk/js?client-id=AZQiAqo_G8vygoAIT9tAL-Z6MQd49xERaY6a3N0ijCRXkubEyMnylsk1qjxNIFM2iAFomcSTfq4yW47O&currency=GBP"
  data-sdk-integration-source="button-factory">
</script>
    <script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');



  function initPayPalButton() {
    paypal.Buttons({
      style: {
        shape: 'rect',
        color: 'gold',
        layout: 'vertical',
        label: 'paypal',

      },
    createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [{
            "amount": {
              "currency_code": "GBP",
              "value": '{{basket.get_total_price}}'
            }
          }]
        });
      },
    onApprove: function (data) {
        var url = "{% url 'checkout:payment_complete' %}"
        return fetch(url, {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'X-CSRFToken': csrftoken,
          },
          body: JSON.stringify({
            orderID: data.orderID
          })
        }).then(function () {
          location.href = '{% url 'checkout:payment_successful' %}';
        })
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();

    </script>

{% endblock %}

templates/checkout/payment_successful.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Payment Successful</h1>
  </div>
  <div class="col-12">
    <p>Order Summary</p>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'account:user_orders'%}">orders</a></p>
  </div>
</div>


{% endblock %}